language: python
python:
  - "3.5"
  - "3.6"
# instalar la ultima version de 'geckodriver'
before_install:
  - ./scripts/install-geckodriver ".geckodriver"
  - export PATH=$PATH:$(readlink -f .geckodriver)
install:
  - pip install -r requirements.txt
git:
  depth: 5
branches:
  only:
    - master
    - develop
addons:
  firefox: latest
script:
  - python manage.py test

# vim:set et sw=2 sts=-1 fdm=indent:
