# Generated by Django 2.0.4 on 2018-04-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feriado',
            options={'ordering': ('fecha',)},
        ),
    ]
